theme: jekyll-theme-cayman
title: "Lab Protocols"

# Default permalink rule for all pages except README
defaults:
  - scope:
      path: ""      # all files
      type: "pages"
    values:
      permalink: /:path/:basename.html
